
 export const ClienteActionTypes = {
    ADD_CLIENTE_START:'ADD_CLIENTE_START',
    ADD_CLIENTE_SUCCESS:'ADD_CLIENTE_SUCCESS',
    ADD_CLIENTE_FAILURE:'ADD_CLIENTE_FAILURE',

    EDIT_CLIENTE_START:'EDIT_CLIENTE_START',
    EDIT_CLIENTE_SUCCESS:'EDIT_CLIENTE_SUCCESS',
    EDIT_CLIENTE_FAILURE:'EDIT_CLIENTE_FAILURE',

    DELETE_CLIENTE_START:'DELETE_CLIENTE_START',
    DELETE_CLIENTE_SUCCESS:'DELETE_CLIENTE_SUCCESS',
    DELETE_CLIENTE_FAILURE:'DELETE_CLIENTE_FAILURE',

    GET_CLIENTE_START:'GET_CLIENTE_START',
    GET_CLIENTE_SUCCESS:'GET_CLIENTE_SUCCESS',
    GET_CLIENTE_FAILURE:'GET_CLIENTE_FAILURE',

    FETCH_COLLECTIONS_START_CLIENTE:'FETCH_COLLECTIONS_START_CLIENTE',
    FETCH_COLLECTIONS_SUCCESS_CLIENTE:'FETCH_COLLECTIONS_SUCCESS_CLIENTE',
    FETCH_COLLECTIONS_FAILURE_CLIENTE:'FETCH_COLLECTIONS_FAILURE_CLIENTE',
}