 /**
 *Types a serem usados no  reducer de Cliente
 * 
 */

 export const ServicoActionTypes = {
    ADD_SERVICO_START:'ADD_SERVICO_START',
    ADD_SERVICO_SUCCESS:'ADD_SERVICO_SUCCESS',
    ADD_SERVICO_FAILURE:'ADD_SERVICO_FAILURE',

    EDIT_SERVICO_START:'EDIT_SERVICO_START',
    EDIT_SERVICO_SUCCESS:'EDIT_SERVICO_SUCCESS',
    EDIT_SERVICO_FAILURE:'EDIT_SERVICO_FAILURE',

    DELETE_SERVICO_START:'DELETE_SERVICO_START',
    DELETE_SERVICO_SUCCESS:'DELETE_SERVICO_SUCCESS',
    DELETE_SERVICO_FAILURE:'DELETE_SERVICO_FAILURE',

    GET_SERVICO_START:'GET_SERVICO_START',
    GET_SERVICO_SUCCESS:'GET_SERVICO_SUCCESS',
    GET_SERVICO_FAILURE:'GET_SERVICO_FAILURE',

    FETCH_COLLECTIONS_START_SERVICO:'FETCH_COLLECTIONS_START_SERVICO',
    FETCH_COLLECTIONS_SUCCESS_SERVICO:'FETCH_COLLECTIONS_SUCCESS_SERVICO',
    FETCH_COLLECTIONS_FAILURE_SERVICO:'FETCH_COLLECTIONS_FAILURE_SERVICO',
}


export const FuncionarioActionTypes = {
    ADD_FUNCIONARIO_START:'ADD_FUNCIONARIO_START',
    ADD_FUNCIONARIO_SUCCESS:'ADD_FUNCIONARIO_SUCCESS',
    ADD_FUNCIONARIO_FAILURE:'ADD_FUNCIONARIO_FAILURE',

    EDIT_FUNCIONARIO_START:'EDIT_FUNCIONARIO_START',
    EDIT_FUNCIONARIO_SUCCESS:'EDIT_FUNCIONARIO_SUCCESS',
    EDIT_FUNCIONARIO_FAILURE:'EDIT_FUNCIONARIO_FAILURE',

    DELETE_FUNCIONARIO_START:'DELETE_FUNCIONARIO_START',
    DELETE_FUNCIONARIO_SUCCESS:'DELETE_FUNCIONARIO_SUCCESS',
    DELETE_FUNCIONARIO_FAILURE:'DELETE_FUNCIONARIO_FAILURE',

    GET_FUNCIONARIO_START:'GET_FUNCIONARIO_START',
    GET_FUNCIONARIO_SUCCESS:'GET_FUNCIONARIO_SUCCESS',
    GET_FUNCIONARIO_FAILURE:'GET_FUNCIONARIO_FAILURE',

    FETCH_COLLECTIONS_START_FUNCIONARIO:'FETCH_COLLECTIONS_START_FUNCIONARIO',
    FETCH_COLLECTIONS_SUCCESS_FUNCIONARIO:'FETCH_COLLECTIONS_SUCCESS_FUNCIONARIO',
    FETCH_COLLECTIONS_FAILURE_FUNCIONARIO:'FETCH_COLLECTIONS_FAILURE_FUNCIONARIO',
}


export const ClienteActionTypes = {
    ADD_CLIENTE_START:'ADD_CLIENTE_START',
    ADD_CLIENTE_SUCCESS:'ADD_CLIENTE_SUCCESS',
    ADD_CLIENTE_FAILURE:'ADD_CLIENTE_FAILURE',

    EDIT_CLIENTE_START:'EDIT_CLIENTE_START',
    EDIT_CLIENTE_SUCCESS:'EDIT_CLIENTE_SUCCESS',
    EDIT_CLIENTE_FAILURE:'EDIT_CLIENTE_FAILURE',

    DELETE_CLIENTE_START:'DELETE_CLIENTE_START',
    DELETE_CLIENTE_SUCCESS:'DELETE_CLIENTE_SUCCESS',
    DELETE_CLIENTE_FAILURE:'DELETE_CLIENTE_FAILURE',

    GET_CLIENTE_START:'GET_CLIENTE_START',
    GET_CLIENTE_SUCCESS:'GET_CLIENTE_SUCCESS',
    GET_CLIENTE_FAILURE:'GET_CLIENTE_FAILURE',

    FETCH_COLLECTIONS_START_CLIENTE:'FETCH_COLLECTIONS_START_CLIENTE',
    FETCH_COLLECTIONS_SUCCESS_CLIENTE:'FETCH_COLLECTIONS_SUCCESS_CLIENTE',
    FETCH_COLLECTIONS_FAILURE_CLIENTE:'FETCH_COLLECTIONS_FAILURE_CLIENTE',
}